version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: blues_dance_postgres
    environment:
      POSTGRES_DB: blues_dance_finder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - blues_dance_network

  redis:
    image: redis:7-alpine
    container_name: blues_dance_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - blues_dance_network

  # Web application (uncomment when ready)
  # web:
  #   build: .
  #   container_name: blues_dance_web
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:password@postgres:5432/blues_dance_finder
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - blues_dance_network

volumes:
  postgres_data:
  redis_data:

networks:
  blues_dance_network:
    driver: bridge