blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/your-org/blues-dance-festival-finder/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/your-org/blues-dance-festival-finder/wiki
    about: Check our documentation and guides
  - name: 🔒 Security Issue
    url: https://github.com/your-org/blues-dance-festival-finder/security/advisories/new
    about: Report a security vulnerability privately