name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 
        Please provide detailed information to help us understand and evaluate your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or need this feature would address
      placeholder: What problem does this feature solve? What need does it address?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: What other approaches have you considered?

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: What type of user would benefit from this feature?
      options:
        - Festival Attendees
        - Teachers
        - Musicians
        - Event Organizers
        - All Users
        - Administrators
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Critical for usage
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases or scenarios where this feature would be helpful
      placeholder: |
        1. As a [user type], I want to [action] so that [benefit]
        2. When [situation], users need to [action]
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If you have any mockups, wireframes, or design ideas, please share them
      placeholder: Drag and drop images here or provide links to designs

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Users can...
        - [ ] The system should...
        - [ ] When..., then...

  - type: checkboxes
    id: considerations
    attributes:
      label: Technical Considerations
      description: Are there any technical aspects we should consider?
      options:
        - label: This feature may require database changes
        - label: This feature may require API changes
        - label: This feature may affect mobile experience
        - label: This feature may require third-party integrations
        - label: This feature may have performance implications

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the feature request
      placeholder: Any additional information that might be helpful...